<a href="https://colab.research.google.com/github/Vib01/Vib01/blob/main/Movie%20Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#importing the dependencies
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
# Data collection and processing
#loading the data from csv to panda frame
movies_data=pd.read_csv('/content/movies.csv')


In [8]:
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [10]:
movies_data.shape

(4803, 24)

In [15]:
#selecting relevant features for recomendation
selected_features=['genres','keywords','tagline','cast','director','vote_average']

In [16]:
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director', 'vote_average']


In [17]:
#replacing null value with null string
for feature in selected_features:
  movies_data[feature]=movies_data[feature].fillna('')

In [19]:
combined_feature=movies_data['genres']+''+movies_data['keywords']+''+movies_data['tagline']+''+movies_data['cast']+''+movies_data['director']+''+str(movies_data['vote_average'])

In [21]:
print(combined_feature)

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...                        
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy RomanceA newlywed couple's honeymoon is...
4800    Comedy Drama Romance TV Moviedate love at firs...
4801    A New Yorker in ShanghaiDaniel Henney Eliza Co...
4802    Documentaryobsession camcorder crush dream gir...
Length: 4803, dtype: object


In [23]:
#converting the text data to feature vectors
vectorizer=TfidfVectorizer()
feature_vectors=vectorizer.fit_transform(combined_feature)

In [25]:
print(feature_vectors)

  (0, 9989)	0.03055833102482272
  (0, 7902)	0.03055833102482272
  (0, 118)	0.03055833102482272
  (0, 15247)	0.03055833102482272
  (0, 26934)	0.03055833102482272
  (0, 18109)	0.03055833102482272
  (0, 117)	0.03055833102482272
  (0, 116)	0.03055833102482272
  (0, 115)	0.03055833102482272
  (0, 113)	0.03055833102482272
  (0, 112)	0.03055833102482272
  (0, 3692)	0.22246402664994003
  (0, 21329)	0.26842612162758306
  (0, 17096)	0.1538475348963807
  (0, 14950)	0.23485436364252482
  (0, 23938)	0.15808249674953892
  (0, 27287)	0.19249152165757807
  (0, 23112)	0.19806296414304875
  (0, 22103)	0.21122697109284042
  (0, 28322)	0.19379207244327648
  (0, 27952)	0.230143776140662
  (0, 22137)	0.15313684400376637
  (0, 19089)	0.2560357846349982
  (0, 18687)	0.08518455372907338
  (0, 27930)	0.12369580164229227
  :	:
  (4802, 7980)	0.3055842078464924
  (4802, 12191)	0.3055842078464924
  (4802, 10912)	0.3055842078464924
  (4802, 7177)	0.3055842078464924
  (4802, 3677)	0.2737078234636616
  (4802, 9406)	0

In [27]:
similarity=cosine_similarity(feature_vectors)

In [28]:
print(similarity)

[[1.         0.07614162 0.02510563 ... 0.01069247 0.01196932 0.01169387]
 [0.07614162 1.         0.03699598 ... 0.02175023 0.01063271 0.01038801]
 [0.02510563 0.03699598 1.         ... 0.01110306 0.01242894 0.01214291]
 ...
 [0.01069247 0.02175023 0.01110306 ... 1.         0.01245935 0.01217262]
 [0.01196932 0.01063271 0.01242894 ... 0.01245935 1.         0.01362623]
 [0.01169387 0.01038801 0.01214291 ... 0.01217262 0.01362623 1.        ]]


In [30]:
print(similarity.shape)

(4803, 4803)


In [35]:
#getting input
movie_name=input("enter your favourite movie name: ")


enter your favourite movie name: Pirates of the Caribbean


In [36]:
#creating a dataset based on input
list_of_all_titles=movies_data['title'].tolist()

In [37]:
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [39]:
#finding the closest match
find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

["Pirates of the Caribbean: At World's End", "Pirates of the Caribbean: Dead Man's Chest", 'Pirates of the Caribbean: On Stranger Tides']


In [40]:
close_match=find_close_match[0]
print(close_match)

Pirates of the Caribbean: At World's End


In [41]:
index_of_movie=movies_data[movies_data.title==close_match]['index'].values[0]
print(index_of_movie)

1


In [42]:
#getting list of similar movies
similarity_score=list(enumerate(similarity[index_of_movie]))

In [43]:
print(similarity_score)

[(0, 0.07614161705781448), (1, 1.0), (2, 0.03699597941533655), (3, 0.010109838604788588), (4, 0.036472608702090334), (5, 0.06039855858673911), (6, 0.02408685540988261), (7, 0.02377248894880549), (8, 0.05122733070449596), (9, 0.023829014695602575), (10, 0.07329622370749261), (11, 0.032940950835258255), (12, 0.4803123926737374), (13, 0.11058409064886895), (14, 0.06521363263843638), (15, 0.02290145160544893), (16, 0.008872275850443997), (17, 0.07649863396796873), (18, 0.0232523802126936), (19, 0.057464525889463484), (20, 0.06313713199847139), (21, 0.008198593734344155), (22, 0.04862839986918503), (23, 0.04573091637580473), (24, 0.0606841763853518), (25, 0.009339724631826777), (26, 0.025023310914826465), (27, 0.11097319126053762), (28, 0.02294059611281398), (29, 0.0248355732488601), (30, 0.07423949980768794), (31, 0.051644665866913464), (32, 0.08088364634398598), (33, 0.023983163484528464), (34, 0.009361302205071129), (35, 0.0098767482127593), (36, 0.009098316465068248), (37, 0.03765246778

In [44]:
#ranking the movies based on similarity score
sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorted_similar_movies)

[(1, 1.0), (12, 0.4803123926737374), (199, 0.47276530592165067), (536, 0.24255317895988063), (3055, 0.1606471647240866), (2035, 0.14577482492522983), (2474, 0.13726898985223518), (1890, 0.13716914785083562), (1063, 0.13366141582018526), (384, 0.1304343196648818), (517, 0.1274027585629111), (2040, 0.12446024017576399), (128, 0.12406788978260211), (2377, 0.12370050519477209), (1577, 0.12223541665323902), (129, 0.12079930484647206), (1581, 0.12039033033768287), (1652, 0.11660230731075201), (2522, 0.11549787830106308), (267, 0.11340910481520594), (262, 0.11232887033224158), (1331, 0.11178882827746325), (27, 0.11097319126053762), (13, 0.11058409064886895), (840, 0.11056189285097955), (2592, 0.1102759106737249), (1017, 0.10932184578967251), (2815, 0.10905508053346132), (326, 0.10897922998769806), (2975, 0.10897167536302581), (2296, 0.10892308308226277), (189, 0.10692058910042351), (1038, 0.10687775378939265), (1747, 0.1066521598177791), (737, 0.105727369736885), (448, 0.10567854807046413), (

In [46]:
print("Movies suggested for you::")
i=1
for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=movies_data[movies_data.index==index]['title'].values[0]
  if(i<30):
    print(i,'.',title_from_index)
    i+=1

Movies suggested for you::
1 . Pirates of the Caribbean: At World's End
2 . Pirates of the Caribbean: Dead Man's Chest
3 . Pirates of the Caribbean: The Curse of the Black Pearl
4 . Anna and the King
5 . Seeking a Friend for the End of the World
6 . Our Kind of Traitor
7 . Arn: The Knight Templar
8 . Don Juan DeMarco
9 . From Hell
10 . Cast Away
11 . Exorcist: The Beginning
12 . The Glass House
13 . Angels & Demons
14 . The Railway Man
15 . Without a Paddle
16 . Thor
17 . Blow
18 . Dragonball Evolution
19 . The Imitation Game
20 . Kingdom of Heaven
21 . The Lord of the Rings: The Fellowship of the Ring
22 . Nim's Island
23 . Battleship
24 . The Lone Ranger
25 . Ronin
26 . Highlander: Endgame
27 . Bedazzled
28 . Star Trek II: The Wrath of Khan
29 . Cinderella


In [48]:
#organizing entire code for presentation
movie_name=input("Enter your favourite movie name:; ")
list_of_all_titles=movies_data['title'].tolist()
find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
close_match=find_close_match[0]
index_of_movie=movies_data[movies_data.title==close_match]['index'].values[0]
similarity_score=list(enumerate(similarity[index_of_movie]))
sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print("Movies suggested for you::")
i=1
for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=movies_data[movies_data.index==index]['title'].values[0]
  if(i<30):
    print(i,'.',title_from_index)
    i+=1

Enter your favourite movie name:; Cars
Movies suggested for you::
1 . Cars
2 . Cars 2
3 . The Fast and the Furious: Tokyo Drift
4 . Witless Protection
5 . Larry the Cable Guy: Health Inspector
6 . The Fast and the Furious
7 . 2 Fast 2 Furious
8 . Cheaper by the Dozen
9 . The Final Destination
10 . Bottle Rocket
11 . The Cable Guy
12 . The Sting
13 . All That Jazz
14 . The Hudsucker Proxy
15 . I Want Someone to Eat Cheese With
16 . Days of Thunder
17 . Turbo
18 . How Do You Know
19 . Death Race
20 . The Woman Chaser
21 . Butch Cassidy and the Sundance Kid
22 . Cast Away
23 . Back to the Future Part II
24 . Stolen Summer
25 . Toy Story
26 . The Wendell Baker Story
27 . Sharkskin
28 . Hum To Mohabbat Karega
29 . Crowsnest
